# Generated by Django 4.2.9 on 2024-03-11 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('category', models.CharField(choices=[('size', 'SIZE'), ('volume', 'VOLUME'), ('weight', 'WEIGHT'), ('currency', 'CURRENCY'), ('length', 'LENGTH'), ('area', 'AREA'), ('temperature', 'TEMPERATURE'), ('time', 'TIME'), ('speed', 'SPEED'), ('number', 'NUMBER')], max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('vote_average', models.FloatField(null=True)),
                ('vote_median', models.FloatField(null=True)),
                ('vote_stddev', models.FloatField(null=True)),
                ('vote_q1', models.FloatField(null=True)),
                ('vote_q3', models.FloatField(null=True)),
                ('vote_iqr', models.FloatField(null=True)),
                ('vote_min', models.FloatField(null=True)),
                ('vote_max', models.FloatField(null=True)),
                ('vote_skewness', models.FloatField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantable_app.quantable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('quantable', 'user')},
            },
        ),
    ]
