# Generated by Django 4.2.9 on 2024-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantable_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantable',
            name='creator_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
