# Generated by Django 4.2.9 on 2024-03-13 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quantable_app', '0002_quantable_creator_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuantablePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_unit', models.CharField(max_length=20)),
                ('quantable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantable_app.quantable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quantable')},
            },
        ),
    ]
