# Generated by Django 4.2.9 on 2024-03-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantable_app', '0003_userquantablepreference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantable',
            old_name='unit',
            new_name='default_unit',
        ),
        migrations.AddField(
            model_name='quantable',
            name='available_units',
            field=models.JSONField(default=list),
        ),
    ]
