# Generated by Django 4.2.9 on 2024-03-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantable_app', '0004_rename_unit_quantable_default_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantable',
            name='is_min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quantable',
            name='pair_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
