# Generated by Django 4.2.9 on 2024-01-15 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentech_app', '0003_webauthncredential_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webauthncredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
